version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "linuxStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jddxc3yl4ps8"
s3_prefix = "linuxStack"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"

